// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zketdtgucabdbfdtlxzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprZXRkdGd1Y2FiZGJmZHRseHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMjQ5NDYsImV4cCI6MjA1ODcwMDk0Nn0.7UR1Epax73cRK8tQh_K7aLrL6lxKPIZzBnAPVqkqnkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);